baseURL = 'https://blog.richtman.com.au/'
languageCode = 'en-us'
title = "Ariel Richtman's technical blog"
theme = 'paper'

[params]

twitter = 'ArielRichtman'
github = 'arichtman'
rss = true

avatar = 'ariel@richtman.com.au'
name = 'Ariel Richtman'
bio = 'Personal tech blog'
